- .eslintrc.json
- .prettierrc
- .vscode/settings.json
- README.md
- package.json
- pnpm-lock.yaml
- src/App.css
- src/pages/_app.tsx
- src/pages/index.tsx
- src/style.css
This PR initializes the ESLint configuration for the web application.
Closes #7
> Initialize ESLint Configuration

- .eslintrc.json
- .prettierrc
- .vscode/settings.json
- package.json
- pnpm-lock.yaml
- src/features/demoAPI/demoAPIActions.ts
- src/features/demoAPI/demoAPISaga.ts
- src/pages/index.tsx
- src/store/index.ts
- src/store/saga.ts
This PR implements redux sagas, a robust side-effect handler. We will use this flow to handle interfacing with Meshtastic devices, as it allows for handling of event-driven data flows.
Closes #4
> Add Redux Saga Framework

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/src/articulation_point.rs
- src-tauri/src/graph_p.rs
- src-tauri/src/main.rs
This algorithm will find articulation points in the graph which are nodes whose removal disconnect the graph. More info about the algorithm and the problem can be found [here](https://www.geeksforgeeks.org/articulation-points-or-cut-vertices-in-a-graph/).
> Implemented Tarjan's Algo for Articulation Points

- src-tauri/src/algorithms/GLOBALMINCUT.md
- src-tauri/src/algorithms/articulation_point.rs
- src-tauri/src/algorithms/globalmincut.rs
- src-tauri/src/algorithms/mod.rs
- src-tauri/src/graph/edge.rs
- src-tauri/src/graph/graph_ds.rs
- src-tauri/src/graph/mod.rs
- src-tauri/src/graph/node.rs
- src-tauri/src/main.rs
This PR separates files into their relevant directories. I also separated Edge and Node structures into their own files for a cleaner code.
> Fixed module hierarchy

- src-tauri/src/algorithms/articulation_point.rs
- src-tauri/src/algorithms/globalmincut.rs
- src-tauri/src/algorithms/mod.rs
- src-tauri/src/algorithms/stoer_wagner.rs
- src-tauri/src/aux_data_structures/binary_heap.rs
- src-tauri/src/aux_data_structures/cut.rs
- src-tauri/src/aux_data_structures/mod.rs
- src-tauri/src/aux_data_structures/stoer_wagner_ds.rs
- src-tauri/src/aux_data_structures/union_find.rs
- src-tauri/src/graph/graph_ds.rs
- src-tauri/src/graph/node.rs
- src-tauri/src/main.rs
As I have discussed [here](https://github.com/ajmcquilkin/Meshtastic-emergency-response-client/pull/62), the previous algorithm, Karger-Stein algorithm, is a probabilistic one. In ~90% of cases it is expected to find the global mincut. However, Stoer-Wagner is an exact and faster algorithm. It finds the global mincut in all cases, and runs much faster. 
This PR implements Stoer-Wagner and adds the following modules:
- Binary Heap
- Union-Find
- Cut
- Stoer-Wagner Graph (enhances Graph by containing Union-Find and contract_edge functionality)
More information about the algorithm can be found [here](https://dl.acm.org/doi/pdf/10.1145/263867.263872).
Closes #75
> Implemented Stoer-Wagner Algorithm

- src-tauri/src/algorithms/articulation_point.rs
- src-tauri/src/algorithms/stoer_wagner.rs
- src-tauri/src/graph/graph_ds.rs
Now using the same graph for both articulation_point and stoer_wagner algorithms for consistency.
> Edited Test Cases for Demo

- src/components/Settings/Settings.tsx
This PR implements the UI for the user configuration settings, namely device ID, device nickname, and device name; as well as a save button.
Closes #101
> Implemented UI for settings

- package.json
- pnpm-lock.yaml
- src/components/Map/MapInteractionPane.tsx
- src/main.tsx
This PR fixes a bug where the popup notification only works on the chrome app, and not the webapp. This PR changes the type of notification and standardizes it.
Duplicate of #190, closed due to difficulties with verison control 
Closes #191
> Implement notifications for tauri app

- src/components/Messaging/ChatBubble.tsx
- src/components/Sidebar/README.md
- src/components/Sidebar/SidebarIcon.tsx
- src/components/Sidebar/TabList.tsx
minor bug fix
* Change type of word break
* Update readme with no serial connect
> minor fixes

- src/components/Sidebar/Sidebar.tsx
This PR fixes #278 through blocking horizontal scrolling on the scrollbar.
Closes #278
> Fixed overflowing sidebar

- src-tauri/bindings/MeshDevice.ts
- src-tauri/src/main.rs
- src-tauri/src/mesh/device/mod.rs
- src-tauri/src/mesh/serial_connection.rs
- src/components/Map/MapView.css
- src/components/Map/MapView.tsx
- src/components/NodeSearch/NodeSearchDock.tsx
- src/components/NodeSearch/NodeSearchResult.tsx
- src/components/pages/MessagingPage.tsx
- src/components/pages/config/ChannelConfigPage.tsx
- src/features/device/deviceSelectors.ts
- src/features/device/deviceSlice.ts
- src/features/map/mapSelectors.ts
- src/features/map/mapSlice.ts
- src/store/index.ts
This PR fixes many small but annoying issues within the application, listed below:
- #166 
- #282 
- #284 
- #292 
- #295 
- Show all channels on channel config page
- Allow for toggling selected node in map view
- Decreased legend text size
- Showed location instead of MAC addr for nodes
Closes #166
Closes #282 
Closes #284 
Closes #292
Closes #295
> Miscellaneous Fixes

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/src/main.rs
- src-tauri/src/mesh/device/connection.rs
- src-tauri/src/mesh/device/handlers.rs
- src-tauri/src/mesh/device/helpers.rs
- src-tauri/src/mesh/device/state.rs
- src-tauri/tauri.conf.json
This PR implements desktop notifications for the application on message receipt. This is shown below. This PR also implements waypoint notifications, although waypoints will currently crash the client.
Closes #283 
Closes #288
> Add text message desktop notifications

- src/components/Map/MapSelectedNodeMenu.tsx
- src/components/Messaging/ChannelDetailView.tsx
- src/components/config/ConfigTitlebar.tsx
Adds overflow scrolling to messages page, and updates direction to show in degrees between 0 and 360
Fixes 
- #302 
- #305
Closes #302
Closes #305
> Minor bugfixes

- package.json
- pnpm-lock.yaml
- src/components/pages/ManageNodePage.tsx
- src/components/pages/ManageWaypointPage.tsx
**Formatting updates for charts:** 
Manage Waypoints
* Expires - Convert to date instead of epoch time
* Latitude & Longitude divided by 1e7
* Owned By - If 0: public; Else: Name of node with corresponding ID; If no corresponding ID, then 'N/A'
Manage Nodes
* ID - Convert to hex to match existing Meshtastic official format
*  Latitude & Longitude divided by 1e7
* User Name - Change to "short name"
Closes #327
> Config tables updates

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/src/main.rs
- src/components/Map/MapView.tsx
- src/features/map/mapSlice.ts
This PR adds edge lines based on the generated backend graph. This PR currently implements the data fetching as a command, although in the future this will need to be an event-based system.
Closes #313
> Add map edge lines

- src-tauri/src/main.rs
Change return type of ap and mincut to string; return only those.
We are now ignoring all but ap and mincut results (can add in to struct later as strings).
Tested in hardware; got results.
> change ap and mincut results to string

- src-tauri/src/main.rs
- src-tauri/src/mesh/device/handlers.rs
- src/features/device/deviceConnectionHandlerSagas.ts
- src/features/device/deviceSagas.ts
This PR automatically dispatches graph edge updates to the UI, which means the graph will display live edge data.
> Graph auto-update with edges

- src/components/Map/MapView.tsx
- src/components/NodeSearch/NodeSearchDock.tsx
- src/utils/map.ts
This PR implements "fly to node" when nodes are selected from the primary node dropdown.
Closes #185
> Implement "fly to node" on map view

- src/App.tsx
- src/components/Sidebar/README.md
- src/components/Sidebar/Sidebar.tsx
- src/components/pages/config/ModuleConfigPage.tsx
- src/utils/routing.ts
> Renamed plugins to modules in codebase

- .github/workflows/main.yml
See https://github.com/tauri-apps/tauri-action
> Experimenting with binary release

- src-tauri/src/ipc/commands/connections.rs
Updated timeout duration from 3s to 15s to handle network latency.
> Bumped initial connection timeout from 3s to 15s

- src-tauri/src/graph/api/update_from_packet.rs
- src-tauri/src/graph/ds/edge.rs
- src-tauri/src/graph/ds/graph.rs
- src-tauri/src/graph/ds/node.rs
> Use DateTime<Utc> instead of NaiveDateTime

- src/components/config/application/About.tsx
- src/components/pages/config/ApplicationSettingsPage.tsx
- src/features/appConfig/slice.ts
- src/locales/en/translation.json
Adds an "About" page within the application settings that should help users report version information.
> Add an "About" page with version info
