meshtastic/network-management-client

.eslintrc.json, package.json, pnpm-lock.yaml, src/features/counter/counterSlice.ts, src/pages/_app.tsx, src/pages/index.tsx, src/store/index.ts, tsconfig.json
This PR initializes the client redux store, and implements a basic counter demo. The `createStore` method from the `redux` package has been deprecated, and as such this project uses the `@reduxjs/toolkit` package.
Closes #3
=> Initialize Redux Store

README.md, package.json, src-tauri/src/main.rs
This PR adds a demo rust unit test within the `src-tauri` directory that is intended to serve as a demo for adding unit testing into the rust backend code. This test will eventually be removed, as it is irrelevant to the functionality of the application. This testing can now be run with the `pnpm run test-rust` command in the parent directory of the client.
Closes #12
=> Implement demo rust unit testing

src-tauri/Cargo.lock, src-tauri/src/GLOBALMINCUT.md, src-tauri/src/globalmincut.rs, src-tauri/src/graph_p.rs, src-tauri/src/main.rs
This probabilistic algorithm finds the global mincut of a graph by contracting an edge until the order of graph is smaller than or equal to 2. The sum of weights of edges between these two nodes is the weight of global mincut. 
Note: The algorithm only returns the weight of mincut. I will need to find a way to recover which original vertex belongs to which cut.
=> Implemented Karger's Algorithm for finding global mincut

src-tauri/src/algorithms/stoer_wagner.rs
After running Stoer-Wagner, we recover the mincut subsets as follows:
```rust
let nodes = vec![u, v, w, x, y, z, a, b];
let (s, t) = recover_mincut(graph_sw, nodes);
```
The tuple (s, t) is a tuple of Vec each of which contains the disjoint subset representing mincut. We pass in the nodes vector because the graph in graph_sw has been modified (all nodes except s-t are deleted due to edge contraction).
=> Added function to recover the mincut

src-tauri/src/algorithms/stoer_wagner.rs, src-tauri/src/aux_functions/edge_factory.rs, src-tauri/src/aux_functions/mod.rs, src-tauri/src/main.rs
We have a vector of distance values, D, and a vector of radio signal qualities, R:
For every x in D: x = (x - min(D)) / (max(D) - min(D))
For every x in R: x = (x - min(R)) / (max(R) - min(R))
Now all values in both D and R are within range (0, 1). The edge weights are then:
weights = (0.5 x D) + (0.5 x R).
We use the module as follows:
```rust
let u = NodeIndex::new(0);
let v = NodeIndex::new(1);
let w = NodeIndex::new(2);
let x = NodeIndex::new(3);
let a = vec![u.clone(), u.clone(), w.clone(), v.clone()];
let b = vec![v.clone(), w.clone(), x.clone(), x.clone()];
let distance = vec![0.45, 0.67, 0.23, 1.2];
let radio_s_quality = vec![5.5, 3.12, 10.3, 2.7];
let edges = edge_factory(a, b, distance, radio_s_quality);
```
Closes #81
=> Added module to merge and normalize edge weights

src/Components/Map/MapNode.tsx, src/Components/Map/MapView.tsx, src/features/device/deviceConnectionHandlerSagas.ts, src/features/device/deviceSelectors.ts, src/features/device/deviceSlice.ts
This PR refactors the redux node handling flow to allow for the rendering of all nodes within the `MapView` component. This change also allows for multiple nodes to be simultaneously connected to the client computer.
Closes #89
=> Display All Nodes on Map

src-tauri/src/aux_functions/edge_factory.rs
High radio signal quality will usually come with low distance, so just scaling the features with minmax will negate the other's magnitude. This PR scales the radio_signal_quality with 1/ln(1+x) before minmax scaling so that large values of radio_signal_quality will result in small values and vice versa.
=> Add another scaler to radio_signal_quality for a better scaling of the features

src-tauri/src/algorithms/globalmincut.rs, src-tauri/src/aux_functions/edge_factory.rs, src-tauri/src/aux_functions/mod.rs, src-tauri/src/aux_functions/take_snapshot.rs, src-tauri/src/graph/edge.rs, src-tauri/src/graph/graph_ds.rs, src-tauri/src/graph/node.rs
This module will take a snapshot of the graph in intervals and save it to a txt file in the following format to be used in #94:
```txt
4
O: a 0
O: b 1
O: c 2
O: d 3
E: a b 0.55
E: a c 0.34
E: b d 0.65
E: b c 0.33
```
First line is the number of nodes in the graph.
Next, for each node, we save its relative position in the graph where 0 is the leftmost node position and 2 is the rightmost position in this graph. "O:" means the line pertains to ordering of graph.
Finally, we save edge per line, for all edges. "E:" means the line pertains to edge of graph.
Currently draft because it needs a better way of selecting leftmost node.
=> Added module to save snapshots of graph to file

src-tauri/src/aux_functions/edge_factory.rs
=> add epsilon while scaling weight to take care of the edge case where min = max

src/components/Map/MapView.tsx, src/components/Sidebar/Sidebar.tsx, src/components/Sidebar/SidebarIcon.tsx, src/features/device/deviceSlice.ts, src/features/panels/panelsSelectors.ts, src/features/panels/panelsSlice.ts, src/store/index.ts
This PR moves the active sidebar panel state into the redux store in a new `panelsSlice` handler. This PR also adds conditional logic in the `MapView` component that allows the rendering of different left-side panels based on which sidebar panel is currently selected.
Closes #113
=> Move Sidebar State into Redux

src-tauri/src/aux_functions/take_snapshot.rs
This PR just changes the functionality that used to save graph snapshot to a txt file. It now returns the string instead of saving it to be passed into python api.
=> Change take_snapshot function to return string

.gitmodules
This PR updates the way the [Meshtastic Protobufs](https://github.com/meshtastic/protobufs) repo is added as a submodule into this project to allow for automatic submodule cloning. To test this, checkout this branch and run `pnpm run rust:dev` and ensure this project builds without errors.
=> Correctly Add Protobuf Submodule

src/components/Map/MapNode.tsx, src/components/NodeSearch/NodeSearchResult.tsx
Currently the `timeSinceLastMessage` value cannot trigger rerenders, meaning if no other renders trigger, this value will always stay at 0. This PR adds `setInterval` hooks within the `MapNode` and `NodeSearchResults` components, which will re-render each component every second.
Closes #117
=> Refresh Node Timeout Value

src-tauri/src/algorithms/stoer_wagner.rs, src-tauri/src/aux_functions/commands.rs, src-tauri/src/aux_functions/mod.rs, src-tauri/src/main.rs, src/components/Sidebar/Sidebar.tsx
This PR makes the three-line change in the Sidebar to pass actual node data to the backend. 
It also implements corresponding null checks to make sure that the app does not panic if there are no nodes detected. Unit tests are updated accordingly.
As of this PR, we make the assumption that our graph is fully connected, or at least that neighbors are known, by artificially adding them to neighbor lists in `generateNeighborInfo` in `DemoData.tsx`. This is a temporary assumption and can easily be changed.
Testing: 
- tested by running `pnpm run rust:dev` with no nodes
=> Run Algorithms on Live Data

src/components/Map/MapView.tsx
Closes #ID
Gets rid of bug where settings page was always superimposed over all other pages
=> Fixed settings bug

src/components/Map/MapView.tsx, src/components/Sidebar/Sidebar.tsx, src/features/panels/panelsSlice.ts
Changed the icons for algorithms in the sidebar to beakers instead of copies of the link
=> Changed icon for algos in sidebar

src-tauri/src/algorithms/stoer_wagner.rs
Accidentally flipped a conditional and returned the highest weighted cut. Fixes that; no changes to functionality
Closes #140
=> [Bugfix] Return Min Cut Correctly

src-tauri/src/main.rs, src-tauri/src/mesh/serial_connection.rs, src/components/Messages/Messages.tsx
This PR fixes a bug in which users on Windows could not connect to serial ports, getting the message "Access is denied" when attempting to connect. This PR resolves this bug, as well as a visual bug on Windows where the `Messages` view will always display a scrollbar.
=> Fix Windows serial connection bug

src-tauri/build.rs, src-tauri/src/lib.rs, src-tauri/src/mesh/serial_connection.rs
This PR updates the build flow to handle namespacing changes introduced in [protobufs/#276](https://github.com/meshtastic/protobufs/pull/276). This PR also adds two additional `match` cases for handling `QueueStatus` and `XmodemPacket` data types.
Closes #208
=> Update protobuf genereation to handle proto namespacing change

src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/algorithms/diffcen.rs, src-tauri/src/algorithms/mod.rs, src-tauri/src/aux_functions/adj_matrix.rs
Closes #202 
This algorithm is a probabilistic simulation of network reliability in T time periods. Specifically, given node a, it calculates the expected number of times a will be able to communicate with the rest of the network. 
It returns a 2D map with the following format:
```txt
{
“a”: {
“a”: sum of its scores,
“b”: E(ab),
“c”: E(ac),
},
“b”: {
“a”: E(ab),
“b”: sum of its scores,
“c”: E(bc),
},
“c”: {
“a”: E(ac),
“b”: E(bc),
“c”: sum of its scores,
}
}
```
The algorithm utilizes matrix powers to simulate paths between all possible nodes and multiplies it with probability q, which is estimated via the maximal eigenvalue v of adjacency matrix where average degree <= v <= max degree. If we consider that in each time unit interval a node tries to communicate with network, then parameter …
=> Added a function to calculate diffusion centralities

src/components/Settings/Settings.tsx, src/features/device/deviceActions.ts, src/features/device/deviceSagas.ts
PR that connects rust backend to current version of settings UI. Allows for changing the `longname` and `shortname` of an active node connected through serial, according to user input in the settings pane. App restarts upon saving.
Will likely be refactored upon implementation of updated UI.
Closes #164
=> Connect device user config to settings UI

src/features/device/deviceConnectionHandlerSagas.ts, src/features/device/deviceSagas.ts, src/features/requests/requestReducer.ts, src/features/requests/requestSelectors.ts, src/store/index.ts
This PR adds a new `request` slice which allows the application to track the state of a given request by a `string` name. In our application we are using this functionality to track the status of commands, but this functionality can be integrated anywhere you can dispatch redux actions. We currently support the following four request states, which are mapped from the `name` of the request:
```typescript
export type IRequestState =
| { status: "IDLE" }
| { status: "PENDING" }
| { status: "SUCCESSFUL" }
| { status: "FAILED"; message: string };
```
These can be attached to a worker as shown below (`deviceSagas.ts`):
```typescript
function* sendMessageWorker(action: ReturnType<typeof requestSendMessage>) {
try {
yield put(requestSliceActions.setRequestPending({ name: action.type }));
yield …
```
=> Add request (command) state management

src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/main.rs, src-tauri/src/mesh/device/connection.rs, src-tauri/src/mesh/device/handlers.rs, src-tauri/src/mesh/device/state.rs, src-tauri/src/mesh/serial_connection.rs, src/components/Messaging/ChannelListElement.tsx, src/components/Onboard/SerialPortOption.tsx, src/components/pages/SerialConnectPage.tsx, src/features/device/deviceSagas.ts, src/features/requests/requestReducer.ts, src/utils/errors.ts
This PR updates the current way the backend handles Rust errors from returning a `Result<OK_TYPE, Box<dyn Error>>` to returning a `Result<OK_TYPE, String>`. This will ensure that the error can be kept on the stack instead of the heap ([link](https://doc.rust-lang.org/rust-by-example/std/box.html)), and makes the error returns more intuitive via the `map_err` method.
This PR also updates the Tauri [commands](https://tauri.app/it/v1/guides/features/command/) to return `Result<OK_TYPE, CommandError>`, where the new `CommandError` struct is defined as follows:
```rust
struct CommandError {
message: String,
}
```
This struct was designed to follow the structure of the JS [Error](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error) shape, specifically the …
=> Update backend error types

src/components/config/ConfigLayout.tsx, src/components/config/ConfigOption.tsx, src/components/pages/config/ChannelConfigPage.tsx, src/components/pages/config/PluginConfigPage.tsx, src/components/pages/config/RadioConfigPage.tsx
This PR adds non-functional config options to the radio, plugin, and channel config pages. While the channel options are generated based on the channels on the connected radio, the radio and plugin configs are hardcoded.
Closes #275
=> Added non-functional options for radio, plugin, and channel config pages

src/components/Onboard/SerialPortOption.tsx, src/components/Sidebar/Sidebar.css, src/components/Sidebar/Sidebar.tsx, src/index.css
Windows will place a scrollbar on any element that overflows, which takes up space within the layout. This PR adds a new `hide-scrollbar` class, which when placed on an element will hide any scrollbars on that element while maintaining scroll functionality.
=> Fix sidebar scroll on windows

src/components/Messaging/ChannelDetailView.tsx, src/features/device/deviceActions.ts
This PR removes the restriction in `requestSendMessage` that forces sending of messages on only the `PRIMARY` channel (index 0).
Closes #270
=> Added multi-channel sending support

src/utils/messaging.ts
This PR ensures that the `MessagingPage` component will show unnamed channels as `"Unnamed Channel"` instead of `""`.
Closes #281
=> Display title for unnamed channels

src-tauri/src/main.rs, src-tauri/src/mesh/serial_connection.rs, src/features/device/deviceConnectionHandlerSagas.ts, src/features/device/deviceSagas.ts
Currently, the application doesn't have UI for reconnecting to a disconnected device. This PR implements a flow that will automatically run the `disconnect_from_serial_port` command and then reload the UI's webview when a serial device loses connection with the application (a `BrokenPipe` error). This will allow the user to reconnect their device as if they just opened the app. This UX will be temporary until a reconnection flow can be established.
Closes #290
=> Reset app on device disconnect

src-tauri/src/mesh/device/handlers.rs
One-line PR that remove mocks generation from position packets.
I was planning to use mock generation to proceed with graph edges/UI without having to have the firmware changes done, but since the forks for them are almost complete, this is no longer necessary. 
No testing
This closes [this ticket](https://app.zenhub.com/workspaces/meshtastic---cosc-098-633f046aebd6cde319822187/issues/gh/dartmouth-cs98/project-22f-meshtastic/105) (on the class repository)
=> removed mocks at runtime:

package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/build.rs, src-tauri/src/mesh/device/mod.rs
This PR removes the existing `TS_RS` type generation suite, per #207.
=> Removed TS generation test suite

src-tauri/src/constructors/init/init_edge_map.rs, src-tauri/src/constructors/init/init_graph.rs, src-tauri/src/data_conversion/distance_constants.rs, src-tauri/src/data_conversion/mod.rs, src-tauri/src/graph/graph_ds.rs
Correctly adds node location info to nodes when creating graph
I added a `add_node_and_location` function to `init_graph` that adds position info to the node fields when it creates nodes. Node: we're not updating nodes right now, just creating them since we're creating an entirely new graph every run. Eventually, update node locations instead of creating new nodes.
Hardware tested with hardcoded fields; they come through and the graph has the correct number of nodes.
=> Adding position info to new node struct fields when graph is created

src-tauri/bindings/ChannelMessagePayload.ts, src-tauri/src/mesh/device/mod.rs, src/components/Messaging/ChannelDetailView.tsx, src/components/Messaging/ChannelListElement.tsx, src/components/Messaging/TextMessageBubble.tsx, src/utils/messaging.ts
This PR fixes a bug where the channel messaging view would crash when the backend is managing any waypoint structs. This was due to a type issue where TS didn't know how to infer the type of the incoming messages, and would crash when a message didn't have a `text` field. This PR fixes this issue by adding in an explicit `"type"` field on the serialized struct ([see here](https://serde.rs/enum-representations.html#internally-tagged)).
Closes #312
=> Allowed for text and waypoint packets to be displayed in messaging UI

src-tauri/src/analytics/algo_result_enums/ap.rs, src-tauri/src/analytics/algo_result_enums/diff_cen.rs, src-tauri/src/analytics/algo_result_enums/mincut.rs, src-tauri/src/analytics/algo_result_enums/most_sim_timeline.rs, src-tauri/src/analytics/algo_result_enums/pred_state.rs, src-tauri/src/analytics/algo_store.rs, src-tauri/src/analytics/algos_config.rs, src-tauri/src/graph/graph_ds.rs, src-tauri/src/main.rs, src/features/device/deviceSagas.ts
Add ability to run algos from the frontend
- Added a state variable with a mutex
- Added a new function for the initialization of the Graph and State (which also calls clone on the arc - [docs](https://doc.rust-lang.org/std/sync/struct.Arc.html))
- Added serialization to the AlgoResults structs and enum
- fixed graph unit tests 
- Client builds successfully 
- command can be invoked from frontend with `__TAURI_INVOKE__("run_algorithms", {bitfield:0b11011}).then(console.log).catch(console.error)`
- No testing with real graph for coherent results yet
=> Command to Run Algos

.gitmodules, src-tauri/src/main.rs, src-tauri/src/mesh/device/connection.rs
Update backend to modularized firmware and don't add edges for nodes without a position in the graph (which are at 0).
- filtered nodes in command (not in graph construction)
...for the first time, you can't run our client at (0.0000 0.0000)! Good luck getting there :)
=> Working node edges

src-tauri/src/main.rs
Change returned ID from String to u32 (so we can look up nodes)
Tested in hardware.
This call may fail if the graph isn't fully populated yet.
=> Return algo result IDs as u32

src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/ipc/commands.rs, src-tauri/src/ipc/helpers.rs, src-tauri/src/main.rs, src-tauri/src/state.rs, src-tauri/tauri.conf.json, src/App.tsx, src/components/SplashScreen/SplashScreen.tsx, src/components/pages/SerialConnectPage.tsx, src/features/device/deviceActions.ts, src/features/device/deviceSagas.ts, src/features/device/deviceSelectors.ts, src/features/device/deviceSlice.ts
Per suggestion by @d4rk4, this PR adds in the ability to programmatically connect to Meshtastic serial devices instead of manually selecting them during application launch. The syntax to do so follows the pattern `EXECUTABLE --port PORT_NAME` or `EXECUTABLE -P PORT_NAME`. If a port is specified, the application will store its name in Tauri state.
The UI layer then queries if the application has a port marked for automatic connection (the `request_autoconnect_port` command). If this command returns a valid port name, the UI layer will then connect to this port as if the user selected it manually (see `SerialConnectionPage.tsx`).
If connection fails, the application will display the serial connection UI as usual.
> **Note:** Running the application with CLI arguments requires the …
=> Add CLI option to programatically connect to devices on startup

README.md, index.html, package.json, src-tauri/tauri.conf.json, src/components/Sidebar/SidebarLogo.tsx
This PR is a tracking PR for a potential project rename.
As we've discussed internally, our project currently doesn't focus specifically on the emergency response scenario, and if we were to double down on this area of focus, we would run the risk of alienating potential users that would find our network and offline management features useful.
From this, I'm proposing we rename the project from "Meshtastic Emergency Response Client" to "Meshtastic Network Management Client." Within our internal conversations I've heard a lot of talk around making sure that Meshtastic networks are reliable and ensuring users can know enough about their network state to maintain working connections. This would certainly not preclude any work that would assist emergency response workers (much to the contrary …
=> Project Rebrand to "Meshtastic Network Management Client"

src-tauri/src/ipc/commands.rs, src-tauri/src/ipc/events.rs, src-tauri/src/ipc/helpers.rs, src-tauri/src/ipc/mod.rs, src-tauri/src/mesh/device/handlers/from_radio/handlers.rs, src-tauri/src/mesh/device/handlers/from_radio/mod.rs, src-tauri/src/mesh/device/handlers/mod.rs, src-tauri/src/mesh/device/mod.rs, src-tauri/src/mesh/device/state.rs, src/App.tsx, src/components/Onboard/SerialPortOption.tsx, src/components/pages/MapPage.tsx, src/components/pages/SerialConnectPage.tsx, src/features/connection/connectionSelectors.ts, src/features/connection/connectionSlice.ts, src/features/device/deviceConnectionHandlerSagas.ts, src/features/device/deviceSagas.ts, src/features/requests/requestReducer.ts, src/features/requests/requestSelectors.ts, src/store/index.ts
This PR changes the condition for a successful serial connection within the `SerialConnectPage` flow. Currently all that is required to "successfully" connect to a serial device is for the `connect_to_serial_port` command to succeed. The issue with this is that, in the event that receiving configuration data from the serial device fails (device config, module config, channels), this failure will be silent to the user. This PR changes this "success" requirement to receiving a `ConfigCompleteId` packet from the serial device within a set timeout period (currently 1500ms). If this timeout is reached, the device will fail to connect and this failure will display on the `SerialConnectPage` UI in a user-readable manner.
This change relies on the `SerialDeviceStatus` struct, shown below:
```rust …
```
=> Fail serial connection flow on configuration timeout

package.json, pnpm-lock.yaml, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/rustfmt.toml, src-tauri/src/device/connection.rs, src-tauri/src/device/serial_connection/handlers.rs, src-tauri/src/device/serial_connection/mod.rs, src-tauri/src/device/state.rs, src-tauri/src/ipc/commands.rs, src-tauri/src/ipc/helpers.rs, src-tauri/src/main.rs, src/components/pages/SerialConnectPage.tsx, src/features/connection/connectionSlice.ts, src/features/device/deviceConnectionHandlerSagas.ts
This PR fixes a Windows-specific bug where nRF52 devices do not respond to serial commands (RAK, TEcho). This PR takes the following steps to solve the problem and improve the async handling within the Rust backend:
1. Enable [serial DTR](https://en.wikipedia.org/wiki/Data_Terminal_Ready) (thanks @thebentern!)
2.  Switches serial libraries from [serialport](https://github.com/serialport/serialport-rs) to [serial2](https://github.com/de-vri-es/serial2-rs) to enable DTR (see above)
3. Move blocking serial read code into the `spawn_blocking` threadpool to eliminate deadlock when blocking on serial IO read
4. Updates worker thread behavior for reliable thread killing on connection failure
5. Updates UI code to reliably disconnect from device on connection timeout
Thanks for the report from …
=> Fix nRF52 connection failure on Windows

package.json, pnpm-lock.yaml, src/App.tsx, src/components/Map/MapView.tsx, src/components/Messaging/ChannelDetailView.tsx, src/components/config/ConfigInput.tsx, src/components/config/ConfigLabel.tsx, src/components/config/ConfigTitlebar.tsx, src/components/config/application/MapConfigPage.tsx, src/components/pages/config/ApplicationSettingsPage.tsx, src/features/map/mapSlice.ts
This PR adds the application settings config page, and a Map tab allowing users to set the Mapbox map style for the map ([see here](https://maplibre.org/maplibre-style-spec/)). This can be demoed with [these styles](https://deck.gl/docs/api-reference/carto/basemap) from Carto.
Note that this configuration **will not** persist on restart. See #374.
Also note that the UI will currently not visually show that the config has updated. See #375.
=> Add Application Settings and Map Style Switching

src-tauri/src/main.rs
This PR fixes Windows production builds due to the following:
1. Exporting development types during production builds
2. Logging permissions issues requiring administrator privileges
Closes #379
=> Fixed windows build failure due to logging permissions

src/components/DefaultTooltip.tsx, src/components/Sidebar/Sidebar.tsx, src/components/Sidebar/SidebarIcon.tsx
Add tooltip text to the sidebar icons so that users can understand the icons when the sidebar is collapsed.
closes: #392
=> enhancement: add tooltip text to sidebar icons

package.json, pnpm-lock.yaml, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/main.rs, src-tauri/tauri.conf.json, src/components/pages/ConnectPage.tsx, src/features/appConfig/appConfigActions.ts, src/features/appConfig/appConfigSagas.ts, src/features/appConfig/appConfigSelectors.ts, src/features/appConfig/appConfigSlice.ts, src/store/index.ts, src/store/saga.ts, src/utils/persistence.ts
This PR adds persistence infrastructure with the [Tauri Store plugin](https://github.com/tauri-apps/tauri-plugin-store). This plugin allows for the storage of arbitrary JSON by string key. This PR also adds Redux infrastructure for getting and setting these values.
This persistence allows for the storage of the last TCP connection state, meaning the `ConnectPage.tsx` component can save and recall the address and port of the last TCP connection the user attempted.
Closes #420
=> Added TCP connection persistence

package.json, pnpm-lock.yaml, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/main.rs, src/api/events.ts, src/components/AppInitWrapper.tsx, src/components/Map/CreateWaypointDialog.tsx, src/components/Messaging/ChannelDetailView.tsx, src/components/Waypoints/WaypointMenu.tsx, src/components/config/application/GeneralConfigPage.tsx, src/components/config/application/MapConfigPage.tsx
This PR replaces the `fern` crate with `tauri-plugin-log`, which unifies logging between the UI and backend layers. The application is configured to log to the following locations:
- `LogDir`: all logs
- `Stdout`: all logs `>= Debug`
- `Webview`:  all logs `>= Info`
Developers should now use the `tauri-plugin-log` NPM package instead of `console`.
=> Updated logging

src/components/SplashScreen/SplashScreen.tsx, src/components/SplashScreen/SplashScreenLogo.css
This PR speeds up the logo splash animation from taking 4.5 seconds down to 2.5 seconds.
I think this animation takes a bit too long, and makes me wonder if the animation is hiding something loading. As far as I can tell, it's not. Tauri has its own splash screen functionality, which appears as a white screen before this logo splash appears.
Since this animation doesn't hide anything, no reason not to make it snappier!
Before:
https://github.com/user-attachments/assets/d12e99a9-0953-4d2f-bdbf-c10e7ff58ce0
After
https://github.com/user-attachments/assets/465793c6-1bce-4ceb-8506-58e5a26bde7d
=> Speed up logo splash animation

package.json, pnpm-lock.yaml, src/components/ErrorFallback.tsx, src/components/Map/MapView.tsx, src/components/config/ConfigInput.tsx, src/components/config/application/MapConfigPage.tsx
Resolves #468
- Makes the config entry for map style URL `required`, so a user cannot enter an empty URL
- Adds `react-error-boundary` as a new dependency
- Adds new `ErrorFallback` component to display errors caught by the ErrorBoundary added above
- This is pretty barebones. Very little styling, just something to display the error message.
- Wraps the `MapView` in the `ErrorBoundary`.
- Locks our Biomejs dependency down to version 1.4
- By adding a dependency (react-error-boundary), I recreated the pnpm lock file. This let pnpm upgrade Biome to a version newer than we support. This caused the linter [to fail across the whole repo](https://github.com/meshtastic/network-management-client/actions/runs/13373027322/job/37345779400), not just files this PR touches.
Below is an image of the …
=> Handle bad map URLs

src-tauri/tauri.conf.json
This fixes the "This app is damaged" message showing up on MacOS preventing users from opening the app without removing the quarantine manually.
MacOS on ARM requires apps to be signed, but you can do what's called an "ad-hoc" signature that has no signer identity from Apple. Instead, you pass the identity `-`.
This does not eliminate [the need to allow the app in your Privacy & Security settings](https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unknown-developer-mh40616/mac). To eliminate this, we will need to [set up codesigning for Mac builds](https://tauri.app/distribute/sign/macos/).
Issue from Tauri tracking this:
https://github.com/tauri-apps/tauri/issues/8763
=> fix: use ad-hoc signing for MacOS builds

src-tauri/Cargo.toml
In preparation for meshtastic crate update to 1.76: https://github.com/meshtastic/rust/pull/48
=> Update minimum supported Rust version

src/components/Sidebar/SidebarLogo.tsx
Fixes part of #494. Namely the collapsing meshtastic icon
=> Fix layout changes when collapsing sidebar

src/components/Map/MapSelectedNodeMenu.tsx, src/components/NodeSearch/NodeSearchResult.tsx
Resolve bugs related to text overflow and misalignment in the Map View components.
i. `NodeSearchResult` component now lists node correctly with ellipsis when the text is too long.
> The related element is now wrapped in a container with a fixed width
> (`11rem`-equivalent) and appended `.truncate` into the class list.
> PS - the Tailwind `.truncate` utility class is equivalent to the combination of
> `.overflow-hidden`, `.text-ellipsis`, and `.whitespace-nowrap`.
ii. `MapSelectedNodeMenu` component now properly wraps the device name element and does not overflow the container.
> The related element now allows text to wrap onto the next line if exceeding
> container's width by applying Tailwind `.break-all` utility class.
Fix #511.
=> fix(ui): :bug: resolve node info misalignment in map view

src/App.tsx, src/components/Sidebar/ConnectionStatus.tsx, src/components/Sidebar/Sidebar.tsx, src/components/connection/RecentConnectPane.tsx, src/components/connection/RecentConnectionCard.tsx, src/components/connection/TcpConnectPane.tsx, src/components/pages/ConnectPage.tsx, src/features/appConfig/api.ts, src/features/appConfig/selectors.ts, src/features/appConfig/slice.ts, src/features/device/api.ts, src/features/device/selectors.ts, src/features/device/slice.ts, src/hooks/useRecentConnectionTracker.ts, src/locales/en/translation.json, src/utils/connections.ts, src/utils/persistence.ts
I recently discovered this project, and am super excited to use (and contributing to) it extensively. The first issue I ran into is that it is a bit of a pain to switch between my nodes, and I kept forgetting which node I was connected to. So, this PR adds a connection status card, a disconnect button, and a list of recent connections. These features allows me to quickly switch between my nodes, and helps me not forget which one I'm connected to.
- Add connection status - shows the current connection
- Add disconnect button - allows connecting to another node without exiting the app
- Add recent TCP connections list - allows quickly switching between recent nodes
- Add current connection page tab to state - avoids needing to click TCP tab every time I want to switch between nodes
- Add …
=> feat: add connection status, disconnect button, and recent tcp connections list
